
version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./evalingon-theme:/var/www/html/wp-content/themes/evalingon-theme
      - ./plugins:/var/www/html/wp-content/plugins
    restart: always


  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    restart: always

